// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVywt_OQZy1T3ltHhyfNPdvaaRleAs0VM',
    appId: '1:82628243400:web:6e202aef69cc3a7aaa1afd',
    messagingSenderId: '82628243400',
    projectId: 'market-f1378',
    authDomain: 'market-f1378.firebaseapp.com',
    storageBucket: 'market-f1378.appspot.com',
    measurementId: 'G-X1XEYR5DML',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMMKGXMbBYbfQ65SWKT-tyvVM2B4IRqYA',
    appId: '1:82628243400:android:f87505442a16f583aa1afd',
    messagingSenderId: '82628243400',
    projectId: 'market-f1378',
    storageBucket: 'market-f1378.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5sLw3qYVD22lsxMzbtxukwhJNyKcypsI',
    appId: '1:82628243400:ios:2bc1f983ed7a57b6aa1afd',
    messagingSenderId: '82628243400',
    projectId: 'market-f1378',
    storageBucket: 'market-f1378.appspot.com',
    iosClientId:
        '82628243400-jntvv9pvdfog11p4d9ubqmg7dgojcmdb.apps.googleusercontent.com',
    iosBundleId: 'com.example.riverpodlearn1',
  );
}
